batch_size: 64
epochs: 100
lr: 0.001
weight_decay: 0.0001
warmup_length: 10
patience: 10
grad_norm: 1.0

device: cuda:0
num_workers: 16
seed: 1234
use_wandb: True

data_dir: data
image_dir: images

# Evaluation
model_path:
checkpoint_path: